version: 2.1
jobs:
    # The test job
    test:
        working_directory: ~/InterVids/Frontend
        docker:
            - image: circleci/node:16-browsers
        steps:
            # Checkout the code from the branch into the working_directory
            - checkout:
                path: ~/InterVids
            # Install project dependencies
            #- run:
             #   name: Switch to Frontend
              #  command: cd ./Frontend
            - run:
                name: List Files
                command: ls
            - run:
                name: Install local dependencies
                command: npm install
            # Test the source code
            - run:
                name: Testing
                command: npm test
workflows:
    test_workflow:
        jobs: 
            - test
